name: boringbookkeepingbusiness
description: The Boring Bookkeeping Business
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  equatable: ^2.0.5
  review_repository:
    path: packages/review_repository
  infinite_carousel: ^1.0.3
  flow_builder: ^0.0.10
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
